#driver_config:
#  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
#  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
#  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>

driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos65
    driver:
      box: learningchef/centos65
      box_url: learningchef/centos65
      network:
      - ["forwarded_port", {guest: 80, host: 8888}]

suites:
  - name: default
    data_bags_path: "test/integration/data_bags" 
    run_list:
      - recipe[mysecurity-cookbook::default]
    attributes:
